### ISSUE TITLE
Ecrã nova estação

### ISSUE THREAD

**Issue by andrecampanha** [ES-Equipa-B/app#22]
Funcionalidades

- [x] Campo de nome (obrigatório)
- [x] Campo de número de telefone (obrigatório, com validação!)
- [x] Botão de criar no canto superior direito - Envia POST para o webserver

![Image](https://user-images.githubusercontent.com/41243996/194921188-41d11e9a-35ae-463e-88ee-ac6943edb9c1.svg)

**Comment by deguchi-04** [comment]
Ja se faz no POST na API
