### ISSUE TITLE
Ecrã definições da aplicação

### ISSUE THREAD

**Issue by andrecampanha** [ES-Equipa-B/app#23]
Funcionalidades:

- [x] Definir como main station
- [x] Definir unidades de medida (Metrico, imperial)

![Image](https://user-images.githubusercontent.com/41243996/195855780-5063a3da-fb06-430d-a954-92bb316f32bc.svg)

**Comment by deguchi-04** [comment]
Ja funciona, os shared preferences ficam salvos no disk
